language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: jtc126@gmail.com
  skip_cleanup: true
  api_key:
    secure: k/N+3IlPydzvPS0/nr0S2YbCC0yB6E2tUojherWIxTX3xJy5CccRz+4aHzeGKQm1BDnirgJEVbHGQ4UyVrHjQzyTs2hcFudJbuMIp0sTq1S83bUHtBpwwmDJyW8fLIneHds5Jxz5EYXtFQ/QHGWxR1oIG642MulOZvEXiXr75IEOk5GMEP/eyFJyBfLjek7KFgsryBnWZ+6WSdHetdTw9JMyhwkZuXC4ReUcu2zz67ZwG83LprjyM2nHccJzdDcM+ySp/zQ1NMClkdMv1B1a9Ixf/sunpMIyS+gf6IobssksNsaDH6aJa1VWurlCVDYSoxihPXAtAimbusgJqARu2/QzbjGJs1DN6shxfI3MLjjq9l+mCpG72MRaojTsYkNFzKjL1KU547pbpqGcaUgXbB9NcCwEQfqpT1P1tzZ9pQVn1KPG7heQIdzVF0piZzQL+7DLaSOhO9nQC2+oE6DZeLrdXCVESIi5llWtgSn+BRus01CpYMRBmcz6HJzLO1fLbAizwdNIm/6tAlaNHSGq88F1PEfc1Sb8hst12TJIa6nh8Rxz6bNZOS5eyO1fnakWXs5YyN2Qez43eQ+7S6mOcY7mHdTehZx1z2/z8247PFvj4BaRdAya6nSnWA81UifsxmkkiOWDK+yJJX7zKzuNOO2Bt/jlsQIHdOZerdP0vG4=
  on:
    tags: true
    repo: jonycheung/deadsimple-less-watch-compiler
env:
  global:
    secure: s6j10HngFDCwENqfsK6AFv1QeL7H7qTQJhCLlQ0KlIjtCxNeRPRGKeLTGxjcSTMiD5YWhp6QBrrEFeH3upvqCQcWI/IQtOG0dfI04EW2aIB/xrw7MF9aTFUmIYraqqFnsehp+7odBP/z7q92oaHdirDtVKMLPl9X1B1rHgRmiQWCvJF9W47Gb62wD0VSwN07hshe9yO9kouV0fthOqU0y/XqTATkXWzEmqbTJs+H6KS6cXYYtd8KoDgHRJDy7ClIdD8jhiPuF339gaG7Yl3lxStIOVAYO+Kxu2+PEVS25UI/JiFvZXHy83FRjsEwJF7b3IN5U2mRe/1StHt5ug9VpgOR82df8whq9xzKmLL5jff2sJuZrrp8n+EB+Hgq/7fU2eXixo3ZFrIFp8jd4EABZdBTtZYrL4VP2ohD5WOWAikHKHFs1ZHJfzNoCeL6+3h7NfD6C1DW0E4J6vuIAflV6+vIc0bX8JI+dV6Vnx0lj7xZyRHlyueXgN3JkbCeNfGXs06BazdAsQSqWkZ0GVMm93xm36ae5aGpAZYZLN1o2wh78BJtNpT9IMU/yUOOv81kmoW2f+6fOtSj3IN8pbpUFDu8Jep5hDz0HD6OoGlihjhDLSdP6kvNzoHdDBs7qsfJoZzPVtd3qIeAWI3n1zQC+vhZpLTPyDjWbmlXtxU0TFY=
